name: Build Mod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Configurar Java 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Dar permisos al wrapper
      run: chmod +x ./gradlew

    - name: Compilar el mod
      run: ./gradlew build

    - name: Subir el `.jar` como artefacto
      uses: actions/upload-artifact@v3
      with:
        name: Portalmod
        path: build/libs/*.jar
